src/app/gestionRegistros/RegistroPredios.jsx
src/components/NavBar.jsx
src/routes/AppRouter.jsx

Creación de la vista para el registro de predios, con las validaciones y rutas adecuadas.

Registro de predios

---

src/app/seguridad/UpdatedPassword.jsx
src/components/NavBar.jsx
src/routes/AppRouter.jsx

Se agrego toda la funcionalidad de actualizar contraseña, vista, logica con el backend, validaciones y rutas.

Actualizacion contraseña

---

src/app/seguridad/UpdatedPassword.jsx

Se mejoró la visualizacion de las validaciones requeridas para las nuevas contraseñas y se puso un limite de 20 caracteres en cada uno de los campos de las contraseñas.

fix: Solucion validaciones en campos de recuperacion de contraseña

---

src/app/auth/Login.jsx
src/app/forgotPassword/ForgotPassword.jsx
src/app/gestionDatos/dispositivosIoT/DispositivosIoTInformation.jsx
src/app/gestionDatos/dispositivosIoT/DispositivosIoTList.jsx
src/app/gestionDatos/lotes/LoteInformation.jsx
src/app/gestionDatos/lotes/LotesList.jsx
src/components/NavBar.jsx
src/routes/AppRouter.jsx

Se agregó la vista y validaciones de forma provisional ya que nada de esto existe en el backend.

Visualizacion informacion dispositivos iot

---

src/app/gestionRegistros/RegistroPredios.jsx

Solucion en el endpoint de registro de predios

fix: Solucion errores endpoint de registro de predios y validaciones

---

src/app/gestionDatos/predios/DeletePlots.jsx
src/app/gestionDatos/predios/PrediosList.jsx

Funcionalidad de inhabilitación de predios hecha, está pendiente el listado de todos los predios (habilitados e inhabilitados).

FEAT: Inhabilitación de predios done

---

src/app/gestionRegistros/RegistroLotes.jsx

Se completó el registro de lotes totalmente funcional. Queda pendiente las modificaciones de mensajes de alerta en back pero ya fue informado al encargado de esa asignación. Se agregó una nueva validación en el predio aignado

FEAT: Registro de lotes funcional y con validaciones

---

src/app/auth/PreRegister.jsx
src/app/gestionDatos/lotes/LotesList.jsx
src/app/gestionDatos/lotes/UpdateLotes.jsx
src/app/gestionDatos/predios/PrediosDetail.jsx
src/app/gestionDatos/predios/PrediosList.jsx
src/components/InputFilterLote.jsx

se creo el componente LotesList, el componente InputFilterLote, y se mejoraron caracteriticas de filtrado de lotes

creacion de listado de lotes

---

src/app/gestionDatos/lotes/DeleteLote.jsx
src/app/gestionDatos/lotes/LotesList.jsx

Inhabilitar lote hecho y se muestran correctamente los inactivos en el listado de lotes ✅.

Inhabilitar lote ✅ 

---

src/app/gestionDatos/Users/id/UserInformation.jsx

FIX: Ya el tipo de persona es mostrado correctamente en la información de usuarios del distrito, pero queda pendiente lo del dirve_folder_id ✅

Informacion usuario distrito ✅ 

---

src/app/gestionDatos/lotes/LoteEdit.jsx
src/app/gestionDatos/lotes/LoteInformation.jsx

Se agrego el campo para cambiar el estado de un lote

fix: Se agrego el campo para cambiar el estado del lote

---

src/app/gestionDatos/Users/PreRegistroDetail.jsx

Envía un correo al usuario con aprobación
Envía un correo en caso de rechazo con su justificación

Se implemento el envio del correo en ambos casos, se modifico los estilos.

---

src/app/gestionDatos/dispositivosIoT/DispositivoEdit.jsx
src/app/gestionDatos/dispositivosIoT/DispositivosIoTInformation.jsx
src/routes/AppRouter.jsx

Se agrego la vista y logica para ver informacion de dispositivos IoT y la edición de dispositivos IoT

feat: Informacion y edicion de dispositivos IoT

---

src/app/gestionDatos/UserEdit/UpdateInformation.jsx

Se eliminó la opción para seleccionar rol desde la vista de edición de usuarios del distrito

FIX: Eliminación de selección de rol

---

src/app/permisos/RolesList.jsx
src/app/permisos/roles-system.jsx

Se volvió a configurar toda la pestaña de roles ya que por cambios en el backend, había dejado de funcionar.
Solo falta la funcionalidad de eliminar roles pero aun falta la ruta desde el back.

Volvió la funcionalidad de roles

---

src/app/gestionDatos/dispositivosIoT/DispositivoEdit.jsx
src/app/gestionDatos/dispositivosIoT/DispositivosIoTInformation.jsx

Se modifico la vista de actualizar informacion de dispositivo IOT con los cambios y validaciones propuestos en el registro de los dispositivos

fix: Correcciones vista de DispositivoEdit

---

src/app/gestionDatos/Users/UsersList.jsx
src/app/infoprediosylotes/LotUsersDetail.jsx
src/app/infoprediosylotes/PlotLotUsersDetail.jsx
src/app/infoprediosylotes/PlotLotUsersList.jsx
src/components/InputFilterPlotLotUser.jsx
src/components/NavBar.jsx
src/routes/AppRouter.jsx

Se creo el apartado de visualizacion de lotes y predios correspondientes a los usuarios, con este ultimo arreglo se da por terminado el modulo1, pensiente de correcciones

creacion de apartado de visualizacion de lotes y predios del propietario

---

src/app/gestionRegistros/RegistroDispositivosIoT.jsx

Se arregló el responsive de registro de dispositivos ✅

FEAT: Responsive en registro de dispositivos done

---

package-lock.json
package.json
src/app/HistorialConsumo/HistorialDistrito.jsx
src/components/NavBar.jsx
src/routes/AppRouter.jsx

Se creo la pestaña de visualizacion de historial de consumo de distrito, se modifico el estilo de la grafica en base a los mockups, se hara la correcta correccion en las historias de usuario, puesto que tambien se agrego un filtrado por fecha, falta correccion del color de los botones que le correspondrá al que realice las funcionalidades de descarga

visualizacion de historial de consumo de distrito 

---

src/app/gestionDatos/dispositivosIoT/DispositivoEdit.jsx

Actualiazación del diseño responsive de la vista de actualizacion de dispositivos iot

fix: Correcciones responsive de DispositivoEdit

---

src/app/gestionDatos/Users/PreRegistrosList.jsx
src/app/permisos/users-system/components/UsersTable.jsx
src/app/permisos/users-system/index.jsx

Se quito email en la tabla de usuarios en gestión de permisos y se remplazo con los roles del usuario
En la tabla pre registro se agrego el nombre y apellido, y se cambio el diseño del estado

Se modificaron campos en las tablas de permisos y pre registro

---

src/app/HistorialConsumo/HistorialPredio.jsx
src/app/HistorialConsumo/HistorialPredioDetail.jsx
src/components/DataTable.jsx
src/components/NavBar.jsx
src/routes/AppRouter.jsx

Se agrego la grafica de consumo por predio y cada una de las caracteristicas propuestas para ese requerimiento como el listar los lotes asociados al predio del cual estamos observando el consumo.

Consumo predio

---

src/app/gestionDatos/Users/id/UserUpdateInformation.jsx

Se arregló que no se mostraba el rol cuando el usaurio va a editar la información propia. ✅

FIX: User Update Personal Infomation done

---

src/app/HistorialConsumo/HistorialLoteDetail.jsx
src/app/HistorialConsumo/HistorialPredioDetail.jsx
src/routes/AppRouter.jsx

Se realizó la visualización del historial de consumo de lote, con su descarga en PDF y CSV ✅

FEAT: Visualización de historial de consumo de lote done

---

src/app/gestionDatos/UserEdit/UpdateInformation.jsx
src/app/gestionDatos/Users/id/UserInformation.jsx
src/app/gestionDatos/lotes/LoteEdit.jsx
src/app/gestionDatos/lotes/LoteInformation.jsx
src/app/gestionRegistros/RegistroDispositivosIoT.jsx
src/app/gestionRegistros/RegistroLotes.jsx
src/app/gestionRegistros/RegistroPredios.jsx
src/app/seguridad/UpdatedPassword.jsx

Se agregaron botones de regresar en vista como de registros, de visualización de información, de edición.  ✅

FEAT: Se agregaron botones para regresar página anterior

---

src/app/gestionDatos/Users/UsersList.jsx
src/app/gestionDatos/dispositivosIoT/DispositivosIoTList.jsx
src/app/gestionDatos/lotes/LotesList.jsx
src/app/gestionDatos/predios/PrediosList.jsx

Se mejoraron y estadarizaron colores para el estado de las listas (predio, lote, usuarios y dispositivos) ✅

FIX: Estandarizando un mismo estado en los listados

---

src/app/HistorialConsumo/HistorialUserPredioDetail.jsx
src/app/HistorialConsumo/HistorialUserPredioList.jsx
src/app/auth/PreRegister.jsx
src/app/gestionDatos/Users/id/UserUpdateInformation.jsx
src/components/NavBar.jsx
src/components/ValidationRules.jsx
src/routes/AppRouter.jsx

Se hicieron los siguientes cambios y adiciones:
- Se agregó el apartado de historial de consumo de predio individual, se agregaron sus respectivas rutas y especificaciones
- se corrigieron errores de modales de pre-registro, para hacerlo dinamico segun errores 400, correo ya registrado y usuario con pre registro ya aprobado.
-  se creo una pantalla de carga para el apartado de pre registro

historial de consumo por predio individual y correcciones

---

src/app/gestionDatos/UserEdit/DeleteSelf.jsx
src/app/gestionDatos/UserEdit/DeleteUsers.jsx
src/app/gestionDatos/Users/PreRegistroDetail.jsx
src/app/gestionDatos/dispositivosIoT/DeleteIoT.jsx
src/app/gestionDatos/lotes/DeleteLote.jsx
src/app/gestionDatos/predios/DeletePlots.jsx
src/app/gestionRegistros/RegistroDispositivosIoT.jsx

Se estandarizaron colores para los botones de inhabilitación de predios, lotes, usuarios y dispositvos ✅

FIX: Corregir botones de inhabilitación (estandarizar)

---

src/components/CsvGenerator.jsx
src/components/PdfGenerator.jsx

Se arreglaron los colores de botones de descarga ✅

FIX: Corregir color de botones para descarga PDF y CSV

---

src/app/forgotPassword/ForgotPassword.jsx
src/app/forgotPassword/RecoverPassword.jsx

- Se muestra la alerta general en el cumplimiento de requeisitos.
- Se muestran los iconos de warniing
- Ya el número no se toma como caracter especial

FIX: Se arreglaron los errores que fueron hechos por pruebas en el RF12

---

src/app/HistorialConsumo/HistorialPredioDetail.jsx

Solucion para poder descargar los informes de consumo de predios en formato pdf y csv

fix: RF 43 - Visualización del historial de consumo por predio del distrito

---

src/app/gestionDatos/predios/PrediosDetail.jsx
src/app/gestionDatos/predios/PrediosUpdate.jsx
src/app/gestionRegistros/RegistroLotes.jsx

Se arregló diseño en la visualización de infromación de predio ✅

HOTFIX: Se arregló diseño de la visualización de información del predio

---

src/app/auth/PreRegister.jsx
src/app/gestionDatos/Users/id/UserUpdateInformation.jsx

- Se corrigió un error de actualizacion de datos personales para la validacion de espacios que reciben cambios
- Se agrego un nuevo modal para validar si hay un pre registro activo en el apartado del mismo

RF-02, RF13/ correcion modal preregistro, correccion espacios de actualizacion de datos

---

src/app/HistorialConsumo/HistorialUserLoteDetail.jsx
src/app/HistorialConsumo/HistorialUserPredioDetail.jsx
src/components/NavBar.jsx
src/components/NavItem.jsx
src/routes/AppRouter.jsx

Se realizó el RF46 - Consulta del historial de consumo de lote individual. Está en espera de back poder ver la gráfica porque aún todos los lotes no tienen datos de consumo. Pero el requerimiento está hecho ✅

FEAT: RF46 - Consulta del historial de consumo de lote individual done

---

src/app/gestionDatos/Users/UsersList.jsx

Se corrigió el modal cuando el ID de filtrado no cuenta con caracteres validos

RF-15 correccion de modal de filtrado por ID de usuario

---

src/app/HistorialConsumo/HistorialUserPredioList.jsx
src/app/gestionDatos/Users/UsersList.jsx
src/app/gestionDatos/dispositivosIoT/DispositivosIoTList.jsx
src/app/gestionDatos/lotes/LotesList.jsx
src/app/gestionDatos/predios/PrediosList.jsx
src/app/infoprediosylotes/PlotLotUsersList.jsx

Se corrigieron los modales de todos los filtros que representaban el error de ID con caracteres invalidos

correccion de los modales de valores de ID con caracteres invalidos

---

src/app/auth/Login.jsx
src/app/forgotPassword/ForgotPassword.jsx

Se pusieron los estados:
1. En el inicio de sesion
- Iniciando sesion…
- Enviando token…
2. En la solicitud para recuperar contraseña:
- Solicitando token…
- Enviando token…

HOTFIX: Se hicieron mejoras en el login y recuperar contraseña

---

src/app/HistorialConsumo/HistorialDistrito.jsx
src/app/HistorialConsumo/HistorialLoteDetail.jsx
src/app/HistorialConsumo/HistorialPredioDetail.jsx
src/app/HistorialConsumo/HistorialUserLoteDetail.jsx
src/app/HistorialConsumo/HistorialUserPredioDetail.jsx

Se corrigio la visualizacion de la grafica segun las fechas seleccionadas y la inhabilitacionn de botones y agregacion de modales cuando nio hay datos alos cuales llamar

RF42-43-44-45-46 correccion de visualizacion de grafica

---

src/app/controloT/ControlBocatoma.jsx
src/components/NavBar.jsx
src/routes/AppRouter.jsx

RF 49 Validaciones de caudal en bocatoma
RF 50 Control de bocatoma
Se añadio la logica para el control de bocatoma mediante grados de apertura.

feat: Logica para el control de la valvula de la bocatoma completada

---

src/app/auth/Login.jsx

Ya se puede pedir nuevo token en login

HOTFIX: Ya se puede solicitar nuevo token en login

---

src/app/gestionDatos/predios/PrediosDetail.jsx

Ya se visualiza el estado del predio en la información

HOTFIX: Ya se visualiza el estado del predio en la información

---

src/app/gestionDatos/dispositivosIoT/DispositivoEdit.jsx

RF36: Se arreglaron las validaciones al momento de actualizar un dispositivo iot, además se bloqueo la edicion de campos sensibles o no editables dentro del formulario

Hotfix. Validacion de envio de formulario para actualizar dispositivos iot

---

src/app/valvulas/ValveFlowUpdate.jsx
src/app/valvulas/ValvesList.jsx

Ya esta listo para probar con IoT

Control de válvulas funcional

---

src/app/gestionDatos/UserEdit/UpdateInformation.jsx

se corrigió una validacion del modal cuando no hay cambios en el formulario de actualizacion de datos

RF-17 correccion de modal de formulario sin cambios

---

src/app/HistorialConsumo/HistorialDistrito.jsx
src/components/PdfGenerator.jsx

Se corrigieron datos de la plantilla de generacion de pdf del componente del mismo, (la corrreccion no pertenece a ningun req en especifico)

Correccion de componente de generar PDF

---

src/app/HistorialConsumo/HistorialDistrito.jsx

Se actualizaronm permisos para visualizacion de historial del distrito

RF-42, actualizacion de permisos en historial

---

src/app/gestionDatos/lotes/LoteEdit.jsx
src/app/gestionDatos/predios/PrediosUpdate.jsx

Se corrigieron validaciones de ingreso de datos en la actualización de predios, y una validación en el estado del lote en la actualización ✅

HOTFIX: PrediosUpdate y LoteUpdate done

---

src/app/auth/PreRegister.jsx

se corrigieron variables para el pre registro en tipo de persona

correccion variables de pre registro

---

src/app/gestionRegistros/RegistroLotes.jsx

Se modificó el registro de lotes, donde se agregó el campo de nombre de cultivo y el tipo de cultivo es un seleccionable ✅ 
Queda pendiente el endpoint de back para traer los tipos de cultivo.

feat: Se modificaron campos de registro de lotes

---

src/app/HistorialConsumo/HistorialPredioDetail.jsx
src/app/HistorialConsumo/HistorialUserPredioDetail.jsx
src/app/gestionDatos/lotes/LoteInformation.jsx
src/app/gestionDatos/lotes/LotesList.jsx
src/app/gestionDatos/predios/PrediosDetail.jsx
src/app/infoprediosylotes/LotUsersDetail.jsx
src/app/infoprediosylotes/PlotLotUsersDetail.jsx

se cambiaron las variables segun la nueva base de datos para mostrar los tipos de cultivo y de suelo en todas las partes con informacion de los mismos

Correccion de variables luego de reestructuracion de la base de datos

---

src/app/controloT/ControlBocatoma.jsx
src/app/facturacion/HistorialFacturasLote.jsx
src/app/misFacturas/MisFacturas.jsx
src/components/DataTable.jsx
src/components/NavBar.jsx
src/routes/AppRouter.jsx

RF55: Se agregó la visualización del historial de facturas por lotes

feat: Visualizacion del historial de facturas por lotes

---

src/app/facturacion/HistorialFacturasLote.jsx
src/components/InputFilterLote.jsx

RF55 Coreccion en los filtros de busqueda, se elimino el filtro de estado ya que no se planeo poner en las HU

fix:  RF55 Filtros de búsqueda

---

src/app/facturacion/GestionFacturas.jsx
src/components/NavBar.jsx
src/routes/AppRouter.jsx

Ya se permiten actualizar los campos de facturación y se valida que al menos 1 campo debe ser editado ✅

FEATURE: Gestión de facturas done ✅ 

---

src/app/gestionDatos/lotes/LoteEdit.jsx

Se agrego el nuevo campo de nombre de cultivo y se mejoro la vista del tipo de cultivo para que se mostrara correctamente el desplegable

fix: Se corrigio la vista y el formulario al editar lotes

---

src/app/facturacion/HistorialFacturasLote.jsx

Se corrigio la vista del listado de lotes al momento de filtra el historial de facturas para que los datos de los lotes se muestren correctamente

fix:  RF55 historial de facturas por lote

---

src/app/auth/PreRegister.jsx

Se mejoró el diseño del pre registro (sección de carga de archivos) ✅

FEATURE: Mejorar diseño del Pre Registro

---

src/app/gestionDatos/Users/id/UserUpdateInformation.jsx

Se hizo un ajuste en el diseño de la vista de acutalización mi información. ✅

FEATURE: Ajuste de diseño en el Actualizar mis datos personales

---

src/app/auth/PreRegister.jsx
src/app/gestionDatos/UserEdit/UpdateInformation.jsx
src/app/gestionDatos/dispositivosIoT/DispositivoEdit.jsx
src/components/ValidationRules.jsx

En el requerimiento de actualización de información de usuarios del distrito, se cambió la lógica de la carga de archivos. Como estamos manejando drive como “bucket de almacenamiento” los archivos no pueden ser traídos a la vista y modificarlo. Por tal razón se planteó de esta manera. ✅

FEATURE: Se modificó la lógica en Edición de usuario del distrito

---

src/app/context/PermissionsContext.jsx
src/components/NavBar.jsx
src/main.jsx

Las opciones están dinámicas según permisos, de los módulos 1 y 2. El 3 está pendiente de desarrollo ✅

Feature: Opciones dinámicas de navbar de los modulos 1 y 2

---

src/app/facturacion/GestionFacturas.jsx

Ya se traen los nuevos campos de back y está funcional ✅

FIX: Actualizando formulario para gestión de tarifas

---

src/app/facturacion/HistorialFacturasLote.jsx

Filtro del historial de facturas por lote totalmente funcional: Se soluciono un bug que existia en el filtrado de fechas del requerimiento 55

fix: Solucion del filtro de fecha requerimiento 55

---

src/app/gestionRegistros/RegistroDispositivosIoT.jsx
src/app/misFacturas/MisFacturasDetails.jsx
src/app/misFacturas/PagarFactura.jsx
src/app/valvulas/ValveFlowUpdate.jsx
src/app/valvulas/ValvesList.jsx
src/routes/AppRouter.jsx

Se cambio lo que decía en grados a listos tanto en registrar dispositivos como en válvulas.
La válvulas ya traen las fechas de registro, y traen el id ubicación dependiendo si es lote o predio
La facturacion ya simula el pago y cambia el estado de la factura

Se modifico registro de dispositivos, mis facturas y las válvulas

---

src/components/NavBar.jsx

Ya la navbar está dinamizada a modulo3 y se arreglaron los problemas mencionados de navbar. ✅

HOTIFX: Arreglando navbar y dinamizando modulo3

---

src/app/facturacion/GestionFacturas.jsx
src/components/ConfirmationModal.jsx

Se hicieron las correcciones que se habían puesto en las issues, lo del modal deconfirmación de cambios y campos de correo y dirección. ✅

HOTFIX: Arreglando requerimientos 52

---

src/app/reportes_y_novedades/ReportesYNovedades.jsx
src/app/reportes_y_novedades/ReportesYNovedadesLotesList.jsx
src/components/DataTable.jsx

Se creo el listado de lotes para reportes,  se agregaron validaciones para lotes inhabilitados en las solicitudes
NOTA: AUN NO EXISTE LOGICA PARA LOS REPORTES (BACKEND)

RF65 agregacion de listado

---

src/app/reportes_y_novedades/reportar_fallos/ReportFailureModal.jsx
src/app/reportes_y_novedades/reportar_fallos/ReportarFallosList.jsx
src/app/reportes_y_novedades/solicitud_caudal/FlowRequestModal.jsx

Se creo el apartado de generar reporte de fallos en el aplicativo  con sus respectivas validaciones

reporte de fallos RF-65

---

src/app/facturacion/GestionFacturas.jsx
src/app/reportes_y_novedades/solicitud_caudal/CancelacionCaudal.jsx
src/app/reportes_y_novedades/solicitud_caudal/CancelationRequestModal.jsx
src/app/reportes_y_novedades/solicitud_caudal/ReportesYNovedades.jsx
src/components/ConfirmationModal.jsx
src/routes/AppRouter.jsx

Se realizó la cencalción de caudal en lote ✅ . Los cambios hechos ya se especificaron en el respectivo documento.

Feature: Solicitud de cancelación de caudal hecha

---

src/app/reportes_y_novedades/atencion_solicitudes-reportes/GestionSolicitudModal.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/GestionSolicitudes-Reportes.jsx
src/app/reportes_y_novedades/solicitud_caudal/FlowRequestModal.jsx
src/app/reportes_y_novedades/solicitud_caudal/ReportesYNovedades.jsx
src/components/InputFilterGestionSolRep.jsx
src/components/NavBar.jsx
src/routes/AppRouter.jsx

se agrego la gestion de solicitudes y reportes, faltan los endpoints de reportes

RF-68 Falta reportes

---

src/app/reportes_y_novedades/solicitud_caudal/ReportesYNovedades.jsx

corrección de rutas en tabla de RF - 61

correccion de rutas en tablas

---

src/app/context/PermissionsContext.jsx
src/app/reportes_y_novedades/reportar_fallos/ReportSupplyModal.jsx
src/app/reportes_y_novedades/reportar_fallos/ReportarFallosList.jsx

Subo hasta el momento mi asignación. Únicamente permite reportar fallos en suministro de agua en lotes. En predio no permite aún porque back todavía no lo ha hecho. Cuando lo arreglen hago el PR respectivo ✅

FEATURE: Reporte de fallos en el suministro de agua

---

src/app/reportes_y_novedades/solicitud_caudal/CancelationRequestModal.jsx
src/app/reportes_y_novedades/solicitud_caudal/ReportesYNovedades.jsx

Se correigieron las issues reportadas del Requerimiento 62 ✅

FEATURE: Corrigiendo issues roportadas del RF62

---

src/app/reportes_y_novedades/atencion_solicitudes-reportes/GestionSolicitudModal.jsx
src/app/reportes_y_novedades/reportar_fallos/ReportFailureModal.jsx
src/app/reportes_y_novedades/solicitud_caudal/FlowRequestModal.jsx

Se creo un nuevo modal para el manejo de errores de conexion a la hora de enviar solicitudes, enviar reportes de error y aceptar ambos desde administracion

creacion de modal error de conexion

---

src/app/reportes_y_novedades/reportar_fallos/ReportFailureModal.jsx

El requerimiento de fallos en el aplicativo enlazado con backend

Requerimiento 65 

---

src/app/reportes_y_novedades/mis-reportes-solicitudes/ReportesSolicitudes.jsx
src/app/reportes_y_novedades/mis-reportes-solicitudes/ReportesSolicitudesDetails.jsx

Se agrego la visualizacion detallada de reportes y solicitudes del sistema

feat: RF74

---

src/app/reportes_y_novedades/reportar_fallos/ReportSupplyModal.jsx
src/app/reportes_y_novedades/solicitud_caudal/CancelationRequestModal.jsx

Los requerimienos 62, 64 y 66 ya fueron completados y correctamente enlazados con backend ✅

FEATURE: RF6, RF64 Y RF66 done

---

src/app/reportes_y_novedades/atencion_solicitudes-reportes/CancelacionDefinitivaModal.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/FallaAplicativoModal.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/FallaSuministroModal.jsx

se arreglaron mensajes de errores del requerimiento especificado

FIX/68- Alertas de errores en las asignaciones

---

src/app/reportes_y_novedades/atencion_solicitudes-reportes/CancelacionDefinitivaModal.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/FallaAplicativoModal.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/FallaSuministroModal.jsx

se reroganizaron la informacion de los modales para cuestiones visuales

Correccion de organizacion de informacion

---

src/app/reportes_y_novedades/atencion_solicitudes-reportes/CancelacionDefinitivaModal.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/FallaAplicativoModal.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/FallaSuministroModal.jsx
src/components/BaseAsignacionModal.jsx

Se creo un componente para manejar las diferentes solicitudes y se cambiaron valores para manerjar los errores en ese modal

manejo de errores y componentes

---

src/app/reportes_y_novedades/gestion_gerencia_informe/control-reportes-intervenciones.jsx
src/app/reportes_y_novedades/gestion_gerencia_informe/gestionar-informe.jsx
src/app/reportes_y_novedades/informe_mantenimiento/crear-informe.jsx
src/app/reportes_y_novedades/informe_mantenimiento/informe-mantenimiento.jsx
src/app/reportes_y_novedades/solicitud_caudal/ReportesYNovedades.jsx

Se modifico el diseño en componentes del requerimiento 70 y 72, para que queden mas acorde a las historias de usuario.

Se modifico el diseño de componentes

---

src/app/reportes_y_novedades/atencion_solicitudes-reportes/Cancelacion_definitiva/CancelacionDefinitivaE.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/Cancelacion_definitiva/CancelacionDefinitivaF.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/Cancelacion_definitiva/CancelacionDefinitivaP.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/Falla_aplicativo/FallaAplicativoE.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/Falla_aplicativo/FallaAplicativoF.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/Falla_aplicativo/FallaAplicativoP.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/GestionSolicitudModal.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/GestionSolicitudes-Reportes.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/SolicitudInfoModal.jsx
src/components/BaseInfoFinalModal.jsx
src/components/BaseInfoFinalModalR.jsx
src/components/BaseInfoModal.jsx
src/components/BaseInfoModalR.jsx
src/components/BaseSolicitudModal.jsx
src/components/InputFilterGestionSolRep.jsx

Se crearon los acceso a ver detalles, asignar y ver informes de mantenimiento como parte de la estructuracion de modulo 6 con 4

Union de modulo 4 y 6 para gestion, asignacion y creacion de mantenimientos

---

src/app/Perfil.jsx
src/components/NavBar.jsx

Se rediseñó la vista del perfil

---

src/app/reportes_y_novedades/atencion_solicitudes-reportes/Falla_aplicativo/FallaAplicativoE.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/Falla_aplicativo/FallaAplicativoF.jsx
src/app/reportes_y_novedades/solicitud_caudal/FlowRequestModal.jsx

se agregaron correcciones necesarias para manejo de errores especificos en solicitudes de cambio de caudal y se modifico la organizacion en la forma de recibir los errores de backend

correcciones y complementos RF-75-RF-76

---

src/app/historialIncidencias/HistorialIncidencias.jsx
src/components/InputFilterIncidencias.jsx
src/components/NavBar.jsx
src/routes/AppRouter.jsx

Se agrego la opcion Historial de Incidencias al Navbar

feat: Se modifico la navbar

---

src/app/Predicciones/distrito/PredictionDistrito.jsx
src/components/NavBar.jsx
src/components/PredictionDistritoChartComponent.jsx
src/routes/AppRouter.jsx

Se agrego la vista y filtrado de predicciones de consumo del distrito, junto con una grafica que muestra de forma visual las predicciones

feat: RF79

---

src/app/NotAuthorized.jsx
src/app/auth/Login.jsx
src/routes/AppRouter.jsx
src/routes/ProtectedRoute.jsx

Queda pendiente terminar permisos de módulo 4, y los de modulo 5 y 6. Pero ya están protegidas las rutas según los permisos ✅

FEATURE: Protección de rutas según permisos

---

package-lock.json
package.json
src/app/facturacion/HistorialFacturasLote.jsx
src/app/reportes_y_novedades/atencion_solicitudes-reportes/GestionSolicitudes-Reportes.jsx
src/app/reportes_y_novedades/gestion_gerencia_informe/gestionar-informe.jsx
src/components/ExcelDownloadTotales.jsx
src/components/InputFilterFacturas.jsx
src/components/PDFDownloadTotales.jsx
src/components/TotalTable.jsx

se creo la parte de auditoria de facturas, totalizacion de las mismas y descarga en PDF y Excel

Auditoria de facturas

---

src/app/Predicciones/PredictionLotChart.jsx
src/components/PredictionLotChartComponent.jsx
src/components/TotalTable.jsx

Predicciones de consumo de lotes del distrito

Creacion predicciones de consumo de lotes del distrito

---

src/app/Predicciones/LotsListPredictions.jsx
src/app/facturacion/HistorialFacturasLote.jsx
src/components/ExcelDownloadTotales.jsx
src/components/InputFilterLotes.jsx
src/components/PDFDownloadTotales.jsx

se corrigieron modales, issues y demas correcciones

correcciones RF78-PDF y EXCEL
